config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    url(r'', include('drdown.core.urls', namespace='core')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('drdown.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^forum/', include('drdown.forum.urls', namespace='forum')),
    url(r'^careline/', include('drdown.careline.urls', namespace='careline')),
    url(r'^medicalrecords/', include('drdown.medicalrecords.urls', namespace='medicalrecords')),
    url(r'^appointments/', include('drdown.appointments.urls', namespace='appointments')),
    url(r'^events/', include('drdown.events.urls', namespace='events')),
    url(r'^notifications/', include('drdown.notifications.urls', namespace='notifications')),
    url(r'^i18n/', include('django.conf.urls.i18n')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

drdown/careline/urls.py
from django.conf.urls import url

from .views import (
    ChecklistDetailView,
    ChecklistRedirectView,
    ChecklistUpdateView
)

app_name = 'careline'
urlpatterns = [
    url(
        regex=r'^$',
        view=ChecklistRedirectView.as_view(),
        name='checklist_list'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=ChecklistDetailView.as_view(),
        name='checklist_detail'
    ),
    url(
        regex=r'^view/update$',
        view=ChecklistUpdateView.as_view(),
        name='checklist_update'
    ),
]

drdown/medicalrecords/urls.py
from django.conf.urls import url
from drdown.medicalrecords.forms.exam_forms import ExamForm
from drdown.medicalrecords.forms.medicalrecords_forms import MedicalRecordForm
from drdown.medicalrecords.forms.static_data_forms import StaticDataForm
from drdown.medicalrecords.forms.medicines_forms import MedicineForm
from drdown.medicalrecords.forms.complaint_forms import ComplaintForm
from drdown.medicalrecords.forms.risk_forms import RiskForm
from drdown.medicalrecords.views import (
    view_medical_record, view_static_data,
    view_medicines, view_complaint, view_exams,
    view_pdf, view_risk, view_curves,
)

app_name = 'medicalrecords'
urlpatterns = [
    url(
        regex=r'list/(?P<username>[\w.@+-]+)/$',
        view=view_medical_record.MedicalRecordsList.as_view(),
        name='list_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new/$',
        view=view_medical_record.MedicalRecordsCreateView.as_view(
            form_class=MedicalRecordForm),
        name='create_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-static-data/$',
        view=view_static_data.StaticDataCreateView.as_view(
            form_class=StaticDataForm),
        name='create_static_data_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-medicine/$',
        view=view_medicines.MedicinesCreateView.as_view(
            form_class=MedicineForm),
        name='create_medicine_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-complaint/$',
        view=view_complaint.ComplaintCreateView.as_view(
            form_class=ComplaintForm),
        name='create_complaint_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-exam/$',
        view=view_exams.ExamCreateView.as_view(
            form_class=ExamForm),
        name='create_exam_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/update-static-data/$',
        view=view_static_data.StaticDataUpdateView.as_view(
            form_class=StaticDataForm),
        name='update_static_data_medicalrecords'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-medicine/$',
        view=view_medicines.MedicinesCreateView.as_view(
            form_class=MedicineForm),
        name='create_medicine'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/update-medicine/(?P<pk>\d+)/$',
        view=view_medicines.MedicinesUpdateView.as_view(
            form_class=MedicineForm),
        name='update_medicine'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/risk/edit/$',
        view=view_risk.RiskUpdateView.as_view(),
        name='update_risk'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/pdf/$',
        view=view_pdf.PDFView.as_view(),
        name='pdf'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/curves/create-height/$',
        view=view_curves.CurvesCreateView.as_view(),
        name='create_curve'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/curves/update-height/(?P<pk>\d+)/$',
        view=view_curves.CurvesUpdateView.as_view(),
        name='update_curve'
    ),
    url(
        regex=r'curves/ajax/$',
        view=view_curves.CurveDataParser.as_view(),
        name='curve_ajax'
    ),
]

drdown/users/urls.py
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~delete/',
        view=views.UserDeleteView.as_view(),
        name='delete'
    ),
    url(
        regex=r'^~patients/$',
        view=views.PatientListViewSelector.as_view(),
        name='patient_list'
    ),
    url(
        regex=r'^~responsible/patients/$',
        view=views.ResponsiblePatientListView.as_view(),
        name='responsible_patient_list'
    ),
    url(
        regex=r'^~healthteam/patients/$',
        view=views.HealthTeamPatientListView.as_view(),
        name='healthteam_patient_list'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

drdown/users/models/model_employee.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import Group, Permission, ContentType
from django.db.models import Q
from django.core.exceptions import ValidationError
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.contrib.auth.models import Group
from ..utils.validators import validate_cpf
from .model_user import User, BaseUserDelete
from .model_patient import Patient
from .model_responsible import Responsible


class Employee(BaseUserDelete, models.Model):

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        limit_choices_to=Q(has_specialization=False),
        verbose_name=_('User')
    )

    cpf = models.CharField(
        help_text=_("Please, enter a valid CPF" +
                    " in the following format: XXX.XXX.XXX-XX"),
        unique=True,
        validators=[validate_cpf],
        max_length=14
    )

    # this is separated from the list because of Django standars
    # if we leave like this we can access the choices from outside
    # example: employee.SPEECH_THERAPHY
    # note: those texts aren't using _() because they are not meant
    # to be translated norshown to the user

    SECRETAY = "SEC"
    ADMINISTRATION = "ADM"
    OTHER = "OTH"

    DEPARTAMENT_CHOICES = (
        (SECRETAY, _('Secretary')),
        (ADMINISTRATION, _('Administration')),
        (OTHER, _('Other')),
    )

    departament = models.CharField(
        _('Departament'),
        null=False,
        choices=DEPARTAMENT_CHOICES,
        help_text=_("The departament where this user works."),
        max_length=30
    )

    # const representig the name of the group wich this model
    # will add to the related user
    GROUP_NAME = "Employees"

    def __str__(self):
        return (self.user.get_username() +
                " - " +
                self.get_departament_display())

    def clean(self, *args, **kwargs):

        try:
            user_db = Employee.objects.get(id=self.id).user

            if self.user != user_db:
                raise ValidationError(
                    _("Don't change users"))
            else:
                pass
        except Employee.DoesNotExist:
            pass

        self.user.clean()

    def save(self, *args, **kwargs):

        # we wan't to add the required permissions to the
        # related user, before saving
        self.user.is_staff = True

        try:
            employee_group = Group.objects.get(name=Employee.GROUP_NAME)
        except Group.DoesNotExist:
            employee_group = Group.objects.create(name=Employee.GROUP_NAME)

        set_permissions(
                Patient,
                employee_group,
                ['change', 'add']
            )

        set_permissions(
                Responsible,
                employee_group,
                ['change', 'add']
            )

        self.user.groups.add(employee_group)

        self.user.clean()
        self.user.save()

        self.clean()

        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')


def set_permissions(model, group, permissions_to_add):
    content_type = ContentType.objects.get_for_model(model)

    if 'add' in permissions_to_add:
        group.permissions.add(Permission.objects.get(
            content_type=content_type, codename__startswith='add_')
        )

    if 'delete' in permissions_to_add:
        group.permissions.add(Permission.objects.get(
            content_type=content_type, codename__startswith='delete_')
        )

    if 'change' in permissions_to_add:
        group.permissions.add(Permission.objects.get(
            content_type=content_type, codename__startswith='change_')
        )

drdown/users/models/model_responsible.py
from django.db import models
from django.db.models import Q
from django.utils.translation import ugettext_lazy as _
from ..utils.validators import validate_cpf
from django.core.exceptions import ValidationError
from django.db.models.signals import post_delete
from django.dispatch import receiver

from .model_user import User, BaseUserSave, BaseUserDelete


class Responsible(BaseUserSave, BaseUserDelete, models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        limit_choices_to=Q(has_specialization=False),
        verbose_name=_('User')
    )

    cpf = models.CharField(
        help_text=_("Please, use enter a valid CPF in" +
                    "the following format: XXX.XXX.XXX-XX"),
        unique=True,
        validators=[validate_cpf],
        max_length=14,
    )

    def have_patient_needing_atention(self):

        response = False
        patients = self.patient_set.all()

        for patient in patients:
            if patient.have_procedures_almost_late():
                response = True
                break

        return response

    def clean(self, *args, **kwargs):

        try:
            user_db = Responsible.objects.get(id=self.id).user

            if self.user != user_db:
                raise ValidationError(
                    _("Don't change users"))
            else:
                pass
        except Responsible.DoesNotExist:
            pass

        self.user.clean()

    def __str__(self):
        return self.user.get_username()

    class Meta:
        verbose_name = _('Responsible')
        verbose_name_plural = _('Responsibles')

drdown/users/models/model_user.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone

from ..utils.validators import validate_phone


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.

    photo = models.ImageField(
        upload_to='media/',
        help_text=_("Photo of user."),
        verbose_name=_('Photo'),
        blank=True,
        null=True,
        max_length=500
    )

    name = models.CharField(
        _('Name'),
        blank=False,
        max_length=255,
        help_text=_("Full user name")

    )

    gender = models.CharField(
        _('Gender'),
        choices=(
            (("Male"), _("Male")),
            (("Female"), _("Female")),
        ),
        blank=False,
        max_length=6,
        null=True
    )

    telephone = models.CharField(
        _('Telephone'),
        blank=False,
        null=True,
        max_length=14,
        validators=[validate_phone],
        help_text=_("(xx)xxxxx-xxxx or (xx)xxxx-xxxx"),

    )

    birthday = models.DateField(
        _('Birthday'),
        help_text=_("xx/xx/xxxx"),
        blank=False,
        null=True
    )

    created_at = models.DateField(
      _('Created at'),
      blank=False,
      null=True
    )

    updated_at = models.DateField(
       _('Updated at'),
       blank=False,
       null=True
    )

    has_specialization = models.BooleanField(
        default=False,
        editable=False
    )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    def get_short_name(self):
        return(self.first_name)

    def age(self):
        today = timezone.datetime.today()
        age = today.year - self.birthday.year - \
            ((today.month,
              today.day) < (self.birthday.month,
                            self.birthday.day))

        if age <= 0:
            diff_month = (today.year - self.birthday.year) * 12 + \
             today.month - self.birthday.month
            age = 0 if diff_month < 6 else 0.5

        return age

    def count_user_specialization(self):

        count = 0

        atributes_to_check = [
            'patient',
            'employee',
            'responsible',
            'healthteam'
        ]

        for attr in atributes_to_check:
            if hasattr(self, attr):
                count += 1

        return count

    def remove_staff(user):

        # we want to remove staff from a user if he is no longer has a
        # specialization that needs it
        user.is_staff = False
        user.save()

    def clean(self, *args, **kwargs):
        data = super(User, self).clean()

        if self.count_user_specialization() > 1:
            error = ValidationError(
               {'user': _("This user is already specialized!")}
            )

            raise error
        else:
            self.has_specialization = (self.count_user_specialization() is 1)

        if isinstance(self.birthday, timezone.datetime):
            self.birthday = self.birthday.date()

        if self.birthday:
            if timezone.localdate().isoformat() < str(self.birthday):
                raise ValidationError(
                    {'birthday': _("The birthday cannot be in the future!")}
                )
            elif (
                timezone.datetime.strptime(str(self.birthday), "%Y-%m-%d") <
                timezone.datetime.strptime("1900-01-01", "%Y-%m-%d")
            ):
                raise ValidationError(
                    {'birthday': _("This birthday is too old.")}
                )

        return data

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class BaseUserDelete():

    def delete(self, *args, **kwargs):
        self.user.has_specialization = False
        self.user.save()
        User.remove_staff(self.user)
        super().delete(*args, **kwargs)


class BaseUserSave():

    def save(self, *args, **kwargs):
        self.user.clean()
        self.user.save()
        self.clean()  # enforce model validation
        super().save(*args, **kwargs)

drdown/users/forms/users_forms.py
from django import forms
from drdown.users.models.model_patient import Patient
from django.utils.translation import ugettext_lazy as _


class PatientSearchForm(forms.Form):

    list_patient = forms.CharField(
        required=False,
        label=_('Search patient!')
    )

drdown/users/templates/users/healthteam_patient_list.html
{% extends "core/base.html" %}
{% load static i18n %}
{% block title %}{% trans "Select a patient" %}{% endblock %}

{% block css %}
{{block.super}}
  <link href="{% static 'users/css/patient_list.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<div class="container">

  <div class="row justify-content-between mb-5">
      <h2 class="text-tertiary">{% trans "Select a patient" %}</h2><br>
    <form class="" action="" method="GET">
      <label>{% trans 'Patient:'%}</label>
      {{ form.list_patient }}
      <button class="btn fa fa-search ml-2 clear-" style="background-color:LightGray" type="submit">{% trans 'Search' %}</button>
    </form>
  </div>

  <div class="row">
    <div class="col">
      <div class="list-group">
        {% for patient in object_list %}
          <a class="patient" style="display:block" href="{% url 'medicalrecords:list_medicalrecords' patient.user.username %}">
            <div class="row">

              <div class="col">
                <div class="row">
                  <div class="col-auto patient-border">
                    <img class="col-auto my-1 img-rounded img-fluid"
                    {% if patient.user.photo %}
                        src="{{patient.user.photo.url}}"
                    {% else %}
                        src="{% static 'users/img/user.png' %}"
                    {% endif %}
                    style="height: auto; width: 100px;">
                  </div>

                  <div class="col">
                      <h4 class="text-tertiary h-blue" >{{ patient.user.name }}</h4>
                      <p class="text-tertiary h-blue"> {% trans 'SES: ' %} {{patient.ses}}</p>
                  </div>
                </div>
              </div>

              {% if patient.responsible %}
                <div class="col-auto responsible-border">
                  <h5 class="text-tertiary h-blue"> {% trans 'Responsible:' %} </h5>
                  <p class="text-tertiary h-blue">  {{patient.responsible.user.name}} </p>
                </div>
              {% endif %}

            </div>
          </a>
          {% empty %}
              <h4>{% trans 'There are no patients for this user.'%}</h4>
          {% endfor %}
      </div>
    </div>
  </div>
  {% include "core/pagination.html" %}
</div>
{% endblock content %}

drdown/users/templates/users/responsible_patient_list.html
{% extends "core/base.html" %}
{% load static i18n %}
{% block title %}{% trans "Select a patient" %}{% endblock %}

{% block content %}
<div class="container">
    <h2 class="text-tertiary">{% trans "Select a patient" %}</h2>

    <div class="list-group">

        {% for patient in object_list %}
            <a href="{% url 'careline:checklist_detail' patient.user.username  %}" class="btn btn-secondary mx-1 my-1" >{% trans "Checklist" %}</a>

                <div class="d-flex w-10 justify-content-start">

                    {% if patient.user.photo %}
                        <img class="d-flex mr-3 rounded-circle" src="{{patient.user.photo.url}}" height="80px" width="80px">
                    {% else %}
                        <img class="d-flex mr-3 rounded-circle" src="{% static 'users/img/user.png' %}" height  ="80px" width="80px">
                    {% endif %}

                    <div class="list-group">
                        <h4 class="list-group-item-heading text-tertiary h-blue" >{{ patient.user.name }}</h4>
                        <p class="text-tertiary h-blue"> {% trans 'SES: ' %} {{patient.ses}}</p>
                    </div>
                </div>

            </a>
            {% empty %}
                <h4>{% trans 'There are no patients for this user.'%}</h4>
            {% endfor %}


    </div>
</div>
{% endblock content %}

drdown/users/templates/users/user_confirm_delete.html
{% extends user.is_authenticated|yesno:"core/base.html,core/base-nav.html" %}

{% load i18n %}

{% block title %}{% trans "Log Out" %}{% endblock %}

{% block content %}
	<h1>{% trans "Delete" %}</h1>

	<form method="post" action="">
	  {% csrf_token %}
	  <p class="lead">{% trans 'Are you sure you want to delete ' %}{{ object }} ?</p>
    <ul class="lead"><li>{% trans "All the data about yourself will be erased and this action can't be undone." %}</li></ul>
	  <button class="btn float-right btn-danger" type="submit">{% trans 'Delete' %}</button>
	</form>

	<a href="{% url 'users:detail' user.username %}"><button class="btn ml-3 btn-secondary mr-2 float-right" type="submit">{% trans 'Cancel' %}</button></a>
{% endblock %}

drdown/users/templates/users/user_form.html
{% extends "core/base.html" %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block script %}
{{block.super}}
  <script type="text/javascript">
    function fMasc(objeto,mascara) {
      obj=objeto
      masc=mascara
      setTimeout("fMascEx()",1)
    }
    function fMascEx() {
      obj.value=masc(obj.value)
    }
    function mTel(tel) {
      tel=tel.replace(/\D/g,"")
      tel=tel.replace(/^(\d)/,"($1")
      tel=tel.replace(/(.{3})(\d)/,"$1)$2")
      if(tel.length == 9) {
        tel=tel.replace(/(.{1})$/,"-$1")
      } else if (tel.length == 10) {
        tel=tel.replace(/(.{2})$/,"-$1")
      } else if (tel.length == 11) {
        tel=tel.replace(/(.{3})$/,"-$1")
      } else if (tel.length == 12) {
        tel=tel.replace(/(.{4})$/,"-$1")
      } else if (tel.length > 12) {
        tel=tel.replace(/(.{4})$/,"-$1")
      }
      return tel;
    }
  </script>

{% endblock %}

{% block content %}
<div class="col-md-6 offset-md-3">
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}" enctype="multipart/form-data">
    {% csrf_token %}

    <div id="div_id_name" class="form-group">
      <label for="id_name" class="col-form-label  requiredField">
          {% trans 'Name' %}<span class="asteriskField">*</span>
      </label>

      <div class="">
        {% if object.name %}
          <input type="text" name="name" maxlength="255" value="{{ object.name }}" class="textinput textInput form-control" required="" id="id_name">
        {% else %}
          <input type="text" name="name" maxlength="255" class="textinput textInput form-control" required="" id="id_name">
          <small id="hint_id_name" class="form-text text-muted">{% trans 'Full user name' %}</small>
        {% endif %}
      </div>
    </div>

    <div id="div_id_gender" class="form-group">
      <label for="id_gender" class="col-form-label  requiredField">
          {% trans 'Gender' %}<span class="asteriskField">*</span>
      </label>
      <div class="">
        <select name="gender" class="select form-control" required="" id="id_gender">
        {% if object.get_gender_display %}
          <option value="{{object.gender}}">{{ object.get_gender_display }}</option>
        {% else %}
          <option value="" selected="">---------</option>
        {% endif %}

        {% if object.gender  == "Male" %}
          <option value="Female">{% trans 'Female' %}</option>
        {% elif object.gender == "Female" %}
          <option value="Male">{% trans 'Male' %}</option>
        {%else%}
          <option value="Female">{% trans 'Female' %}</option>
          <option value="Male">{% trans 'Male' %}</option>
        {% endif %}
        </select>
      </div>
    </div>

    <div id="div_id_telephone" class="form-group">
      <label for="id_telephone" class="col-form-label  requiredField">
          {% trans 'Telephone' %}<span class="asteriskField">*</span>
      </label>
      <div class="">

            {% for error in form.telephone.errors %}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
            {% endfor %}

        {% if object.telephone %}
          <input type="text" name="telephone" value= "{{ object.telephone }}" maxlength="14" class="textinput textInput form-control" required id="id_telephone" onkeydown="javascript: fMasc( this, mTel );" />
        {% else %}
          <input type="text" name="telephone" maxlength="14" class="textinput textInput form-control" required id="id_telephone" onkeydown="javascript: fMasc( this, mTel );" />
        {% endif %}
        <small id="hint_id_telephone" class="form-text text-muted">(xx)xxxxx-xxxx or (xx)xxxx-xxxx</small>
      </div>
    </div>

    <label>{% trans 'Birthday' %}<span class="asteriskField">*</span>
    </label>

    {% for error in form.birthday.errors %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
    {% endfor %}

    {% if object.birthday %}
      <input type="date" name="birthday" value="{{ object.birthday | date:'Y-m-d' }}" required=true class="form-control">
    {% else %}
      <input type="date" name="birthday" required=true class="form-control">
    {% endif %}
    <span class="validity"></span>

    <div id="div_id_photo" class="form-group">
      <label for="id_photo" class="col-form-label ">
        {% trans 'Photo' %}
      </label>
      <div class="">
        <input type="file" name="photo" class="clearablefileinput" id="id_photo" accept=".png, .jpg, .jpeg, .gif">
        <small id="hint_id_photo" class="form-text text-muted">{% trans 'Photo of user' %}.</small>
       </div>
  </div>

    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-success float-right">{% trans 'Update' %}</button>
      </div>
    </div>
  </form>
  {% if object.name %}
    <a href="{% url 'users:detail' user.username%}"><button type="submit" class="btn btn-danger mr-2 float-right">{% trans 'Cancel' %}</button></a>
  {% endif %}
</div>
{% endblock %}

drdown/users/templates/users/user_list.html
{% extends "core/base.html" %}
{% load static i18n %}
{% block title %}{% trans "Members" %}{% endblock %}

{% block content %}
<div class="container">
  <h2>{% trans "Users" %}</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}