config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    url(r'', include('drdown.core.urls', namespace='core')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('drdown.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^forum/', include('drdown.forum.urls', namespace='forum')),
    url(r'^careline/', include('drdown.careline.urls', namespace='careline')),
    url(r'^medicalrecords/', include('drdown.medicalrecords.urls', namespace='medicalrecords')),
    url(r'^appointments/', include('drdown.appointments.urls', namespace='appointments')),
    url(r'^events/', include('drdown.events.urls', namespace='events')),
    url(r'^notifications/', include('drdown.notifications.urls', namespace='notifications')),
    url(r'^i18n/', include('django.conf.urls.i18n')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

drdown/events/urls.py
from django.conf.urls import url
from drdown.events.views.view_event import EventsListView
from drdown.events.views.view_event import CalendarEventsListView
from drdown.events.views.view_event import EventsCreateView
from drdown.events.views.view_event import EventsUpdateView
from drdown.events.views.view_event import EventsDeleteView
from django.views.generic import TemplateView

app_name = 'events'

urlpatterns = [
    url(
        regex=r'^$',
        view=EventsListView.as_view(),
        name='list_events'
    ),
    url(
        regex=r'^new/$',
        view=EventsCreateView.as_view(),
        name='create_event'
    ),
    url(
        regex=r'^update/(?P<pk>\d+)/$',
        view=EventsUpdateView.as_view(),
        name='update_event'
    ),
    url(
        regex=r'^delete/(?P<pk>\d+)/$',
        view=EventsDeleteView.as_view(),
        name='delete_event'
    ),
    url(
        regex=r'^calendar/$',
        view=CalendarEventsListView.as_view(),
        name='calendar'
    ),

]

drdown/events/models/model_events.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import date

from drdown.notifications.utils import mail
from drdown.users.models import User

from django.db.models import Q


class Events(models.Model):

    name = models.CharField(
        _('Name'),
        help_text=_('Name of event'),
        max_length=50,
        default=""
    )
    location = models.CharField(
        _('Location'),
        help_text=_('Location of event'),
        max_length=50,
        default=""
    )
    date = models.DateField(
        _('Date'),
        help_text=_('Date of event'),
        max_length=50
    )
    time = models.TimeField(
        _('Time'),
        help_text=_('Time of event'),
        max_length=50
    )
    description = models.TextField(
        _('Description'),
        help_text=_('Description from event'),
        max_length=500,
        blank=True,
    )

    organize_by = models.CharField(
        _('Organize by'),
        max_length=80,
        help_text=_('Person who organize the event'),
    )

    free = models.BooleanField(default=False)

    value = models.FloatField(
        _('Value of event'),
        help_text=_('Event value if that is paid'),
    )

    def clean(self, *args, **kwargs):
        if self.date:
            if date.today() + timezone.timedelta(days=1) > self.date:
                raise ValidationError(
                    {'date':
                        _("The date cannot be in today or past!")}
                )

    def save(self, *args, **kwargs):

        if Events.objects.filter(id=self.id).count() > 0:

            mail.send_event_update_message(
                user_list=User.objects.filter(
                    Q(patient__isnull=False) | Q(responsible__isnull=False)
                ).values_list('email', flat=True),
                event=self
            )

        else:

            mail.send_event_creation_message(
                user_list=User.objects.filter(
                    Q(patient__isnull=False) | Q(responsible__isnull=False)
                ).values_list('email', flat=True),
                event=self
            )

        super(Events, self).save(*args, **kwargs)

    class Meta:
        verbose_name = _("Event")
        verbose_name_plural = _("Events")

drdown/events/views/view_event.py
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.views.generic import ListView
from drdown.events.models.model_events import Events
from django.urls import reverse
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin


class BaseViewPermissions(UserPassesTestMixin):

    def test_func(self):
        return hasattr(self.request.user, 'employee')


class EventsListView(ListView):
    model = Events
    slug_field = 'name'
    slug_url_kwarg = 'name'
    template_name = 'events/events_list.html'


class EventsCreateView(BaseViewPermissions, CreateView):
    model = Events
    template_name = 'events/events_form.html'
    fields = [
        'free',
        'location',
        'name',
        'date',
        'time',
        'description',
        'organize_by',
        'value',
    ]

    success_url = reverse_lazy(
        viewname='events:list_events',
    )


class EventsUpdateView(BaseViewPermissions, UpdateView):
    model = Events
    template_name = 'events/events_form.html'
    fields = [
        'free',
        'location',
        'name',
        'date',
        'time',
        'description',
        'organize_by',
        'value',
    ]

    def get_object(self):
        event = Events.objects.get(
            pk=self.kwargs.get('pk')
        )
        return event

    success_url = reverse_lazy(
        viewname='events:list_events',
    )


class EventsDeleteView(BaseViewPermissions, DeleteView):
    model = Events
    success_url = reverse_lazy(
        viewname='events:list_events',
    )


class CalendarEventsListView(ListView):
    model = Events
    slug_field = 'name'
    slug_url_kwarg = 'name'
    template_name = 'events/events_calendar.html'

drdown/events/templates/events/events_calendar.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}
  {% trans "Calendar of Events" %}
{% endblock %}

{% block script %}

  <script src="{% static 'events/js/jquery.min.js'%}"></script>
  <script>
     var jqCal = jQuery.noConflict(false);
  </script>

  <script src="{% static 'events/js/moment.min.js'%}"></script>
  <script src="{% static 'events/js/fullcalendar.min.js'%}"></script>

  {% if request.LANGUAGE_CODE == 'pt-br' %}
    <script src="{% static 'events/js/pt-br.js'%}"></script>
  {% elif request.LANGUAGE_CODE == 'en' %}
    <script src="{% static 'events/js/en-gb.js'%}"></script>
  {% endif %}

  <link rel="stylesheet" href="{% static 'events/css/fullcalendar.min.css'%}">

  <script>
    jqCal(document).ready(function() {
        jqCal('#calendar').fullCalendar({
            header: {
              left: 'prev,next today',
              center: 'title',
              right: 'month,listWeek'
            },
            editable: true,
            eventLimit: true, // allow "more" link when too many events
            events: [
                {% for event in events_list %} {
                    title: "{{ event.name }}",
                    start: '{{ event.date|date:"Y-m-d" }}' + 'T' + '{{ event.time|time:"H:i" }}',
                    end: '{{ event.date|date:"Y-m-d" }}',

                },
                {% endfor %}
            ]
        });
    }).fullCalendar('gotoDate', currentDate);
  </script>

{% endblock script %}

{% block content %}
  <div class="container">

    <div class="row mt-3 float-right">
      <div class="col mt-2 mr-5">
        <a href="{% url 'events:list_events' %}" style="font-size:20px; text-decoration:underline;" class="text-tertiary">
          <i class="fa fa-angle-double-left" style="font-size:25px;"></i>
          {% trans "List of Events" %}
        </a>
      </div>
    </div>

    <div class="row">
      <div class="row mt-3 mb-3">
        <div class="col">
          <h1>{% trans 'Calendar of Events'%}</h1>
        </div>
      </div>
    </div>

    <style>

    calendar {
      margin: 40px 10px;
      padding: 0;
      font-family: "Lucida Grande",Helvetica,Arial,Verdana,sans-serif;
      font-size: 14px;
    }

    #calendar {
      max-width: 900px;
      margin: 0 auto;
    }

    </style>

    <div class="mt-2 mb-2" id='calendar'></div>

  </div>

{% endblock %}

drdown/events/templates/events/events_form.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}
  {% url 'events:create_event' as url %}
  {% if request.path == url %}
    {% trans "New Event" %}
   {% else %}
    {% trans "Edit Event" %}
  {% endif %}
{% endblock %}

{% block script %}
<script type="text/javascript">
  function toggle(checkboxID, toggleID) {
     var checkbox = document.getElementById(checkboxID);
     var toggle = document.getElementById(toggleID);
     if (checkbox.checked){
        toggle.readOnly= true;
        toggle.value=0;
     }
     else {
      toggle.readOnly= false;
     }
  }
</script>

<script>
  function check(input, checkboxID) {
  var checkbox = document.getElementById(checkboxID);
   if (input.value <= 0 && checkbox.checked == false) {
     input.setCustomValidity('The value of event must be greater than 0. If the event is free, please check true in right side of the screen.');
   } else {
     // input is fine -- reset the error message
     input.setCustomValidity('');
   }
 }
</script>

<script>
  function check_br(input, checkboxID) {
  var checkbox = document.getElementById(checkboxID);
   if (input.value <= 0 && checkbox.checked == false) {
     input.setCustomValidity('O valor do evento deve ser maior que 0. Caso seja gratuito, favor marcar o campo à direita');
   } else {
     // input is fine -- reset the error message
     input.setCustomValidity('');
   }
 }
</script>

{% endblock script %}

{% block content %}
  <div class="container">
    <div class="row">
      {% if form.date.errors %}
        <div class="alert alert-danger col" role="alert">{{ form.date.errors }}</div>
      {% endif %}
    </div>
    {% if object %}
      <h2>{% trans 'Edit Event' %}</h2>
    {% else %}
      <h2>{% trans 'New Event' %}</h2>
    {% endif %}
    <form method='post' class="mt-3">
      {% csrf_token %}
      <div class="row">
        <div class="form-group col">
          <label>{% trans 'Name' %}*</label>
          {% if object.name %}
            <input class="form-control" type="text" name="name" maxlength="50" required id="id_name" value="{{ object.name }}"/>
            <small class="text-muted">{% trans 'Enter a event name' %}</small>
          {% else %}
            <input class="form-control" type="text" name="name" maxlength="50" required id="id_name"/>
            <small class="text-muted">{% trans 'Enter a event name' %}</small>
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="form-group col">
          <label for="id_date">{% trans 'Date' %}*</label>
          {% if object.date %}
            <input class="form-control" type="date" name="date" required id="id_date" value="{{ object.date | date:'Y-m-d' }}" />
            <small class="text-muted">{% trans 'Enter a event date' %}</small>
          {% else %}
            <input class="form-control" type="date" name="date" required id="id_date" />
            <small class="text-muted">{% trans 'Enter a event date' %}</small>
          {% endif %}
        </div>

        <div class="form-group col">
          <label for="id_time">{% trans 'Time' %}*</label>
          {% if object.time %}
            <input class="form-control" type="time" name="time" required id="id_time" value="{{ object.time |time:'H:i' }}"/>
            <small class="text-muted">{% trans 'Enter a event time' %}</small>
          {% else %}
            <input class="form-control" type="time" name="time" required id="id_time"/>
            <small class="text-muted">{% trans 'Enter a event time' %}</small>
          {% endif %}
        </div>
      </div>

      <div class="row">
        <div class="form-group col">
          <label for="id_organize_by">{% trans 'Organize by' %}*</label>
          {% if object.organize_by %}
            <input class="form-control" type="text" name="organize_by" maxlength="80" required id="id_organize_by" value="{{ object.organize_by }}"/>
            <small class="text-muted">{% trans 'Enter a event organizer' %}</small>
          {% else %}
            <input class="form-control" type="text" name="organize_by" maxlength="80" required id="id_organize_by" />
            <small class="text-muted">{% trans 'Enter a event organizer' %}</small>
          {% endif %}
        </div>
        <div class="form-group col">
          <label for="id_location">{% trans 'Location' %}*</label>
          {% if object.location %}
            <input class="form-control" type="text" name="location" maxlength="80" required id="id_location" value="{{ object.location }}"/>
            <small class="text-muted">{% trans 'Enter a event location' %}</small>
          {% else %}
            <input class="form-control" type="text" name="location" maxlength="80" required id="id_location"/>
            <small class="text-muted">{% trans 'Enter a event location' %}</small>
          {% endif %}
        </div>
      </div>

      <div class="row">
        <label class="col" for="id_value">{% trans 'Value of event' %}*</label>
        <div class="col-auto">
          {% if object.free %}
            <small class="text-muted mr-1">{% trans 'Event is free?' %}</small>
            <input type="checkbox" name="free" onclick="toggle('id_free', 'id_value')" id="id_free" checked/>
          {% else %}
            <small class="text-muted mr-1">{% trans 'Event is free?' %}</small>
            <input type="checkbox" onclick="toggle('id_free', 'id_value')" name="free" id="id_free"/>
          {% endif %}
        </div>
      </div>
      <div class="form-group">
        {% if object.free %}
          <input class="form-control" type="number" name="value" step="0.010" required id="id_value"  value="0" readonly/>
          <small class="text-muted">{% trans 'Enter a value event' %}</small>
        {% elif object.value %}
          {% if request.LANGUAGE_CODE == 'pt-br' %}
            <input class="form-control" type="number" name="value" required id="id_value" step="0.001" oninput="check_br(this,'id_free')" value="{{ object.value | stringformat:'g' }}"/>
          {% elif request.LANGUAGE_CODE == 'en' %}
            <input class="form-control" type="number" name="value" required id="id_value" step="0.001" oninput="check(this,'id_free')" value="{{ object.value | stringformat:'g' }}"/>
          {% endif %}
          <small class="text-muted">{% trans 'Enter a value event' %}</small>
        {% else %}
          {% if request.LANGUAGE_CODE == 'pt-br' %}
            <input class="form-control" type="number" name="value" required id="id_value" step="0.001" step="0.01" oninput="check_br(this,'id_free')" />
          {% elif request.LANGUAGE_CODE == 'en' %}
            <input class="form-control" type="number" name="value" required id="id_value" step="0.001" oninput="check(this,'id_free')" />
          {% endif %}
          <small class="text-muted">{% trans 'Enter a value event' %}</small>
        {% endif %}
      </div>

      <div class="form-group">
        <label for="id_description">{% trans 'Description' %}*</label>
        {% if object.description %}
          <textarea class="form-control" name="description" cols="40" rows="5" maxlength="500" id="id_description" required>{{object.description}}</textarea>
          <small class="text-muted">{% trans 'Enter event description and details' %}</small>
        {%else%}
          <textarea class="form-control" name="description" cols="40" rows="5" maxlength="500" id="id_description" required></textarea>
          <small class="text-muted">{% trans 'Enter event description and details' %}</small>
        {% endif %}
      </div>
      <button type="submit" class="btn btn-success float-right">{% trans 'Submit' %}</button>
    </form>
    <a href="{% url 'events:list_events' %}"><button type="submit" class="btn btn-danger mr-1 float-right">{% trans 'Cancel' %}</button></a>
  </div>
{% endblock %}

drdown/events/templates/events/events_list.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}
  {% trans "Events" %}
{% endblock %}

{% block css %}
  {{block.super}}
  <link href="{% static 'events/css/events.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}

  <div class="container">

    <div class="row mb-5">
      <div class="col">
        <h1>{% trans 'Events'%}</h1>
      </div>
      {% if user.employee %}
        <div class="col mt-1">
          <a href="{% url 'events:create_event'%}" class="btn btn-secondary float-right" >{% trans "New" %}</a>
        </div>
      {% endif %}
    </div>

    <div class="row mb-3 ml-1">
      <a href="{% url 'events:calendar'%}" style="font-size:20px; text-decoration:underline;" class="text-tertiary">
        <i class="fa fa-calendar" style="font-size:25px;" aria-hidden="true" ></i>
        {% trans "Calendar of Events" %}
      </a>
    </div>

    <div class="accordion" id="accordionmenu3">
      {% for event in events_list %}

        <div class="row" id="heading{{ event.pk }}">
          <a class="event border-right" style="display:block; width:80%;" data-toggle="collapse" href="#collapse{{ event.pk }}" role="button" >
            <h4 class="lead">{{ event.name }}</h4>
            <small class="text-muted">{{ event.date }}</small>
          </a>

          {% if user.employee %}
            <div class="col-1 border-bottom mt-4">
               <a href="{% url 'events:update_event' event.pk %}" class="btn btn-secondary " >{% trans "Edit" %}</a>
            </div>
            <div class="col-1 border-bottom mt-4">
              <a data-toggle="modal" data-target="#event-{{ event.name }} delete_event"  href="" class="btn btn-danger space ">{% trans "Delete" %}</a>
            </div>
          {% endif %}
        </div>

        <div id="collapse{{ event.pk }}" class="collapse" data-parent="#heading{{ event.pk }}">
          <div class="card-body">
            <div class="row">
              <label class="col"><strong>{% trans 'Date' %} :</strong></label>
              <label class="col"><strong>{% trans 'Time' %} :</strong></label>
              <label class="col"><strong>{% trans 'Value' %} :</strong></label>
            </div>
            <div class="row">
              <div class="col mx-3 alert alert-dark" role="alert">
                <div class="col">{{ event.date }}</div>
              </div>
              <div class="col mx-3 alert alert-dark" role="alert">
                <div class="col">{{ event.time }}</div>
              </div>
              {% if event.free %}
                <div class="col mx-3 alert alert-dark" role="alert">
                  <div class="col">{% trans 'Free Event' %}</div>
                </div>
              {% else %}
                <div class="col mx-3 alert alert-dark" role="alert">
                  <div class="col">R$ {{ event.value|floatformat:2 }}</div>
                </div>
              {% endif %}
            </div>
            <div class="row">
              <label class="col"><strong>{% trans 'Organize by' %} :</strong></label>
              <label class="col"><strong>{% trans 'Location' %} :</strong></label>
            </div>
            <div class="row">
                <div class="col mx-3 alert alert-dark" role="alert">
                  <div class="col">{{ event.organize_by }}</div>
                </div>
                <div class="col mx-3 alert alert-dark" role="alert">
                  <div class="col">{{ event.location }}</div>
                </div>
            </div>
            <div class="row">
              <label class="col"><strong>{% trans 'Description' %}</strong></label>
            </div>
            <div class="row">
              <div class="col mx-3 alert alert-dark" role="alert">
                <div class="col">{{ event.description }}</div>
              </div>
            </div>
          </div>
        </div>
        <div class="modal fade" id="event-{{ event.name }} delete_event" role="dialog">
          <div class="modal-dialog modal-sm modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">{% trans 'Confirm delete' %}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                <p>{% trans 'Are you sure you want to delete this event?' %}</p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>
                <form method="post" action="{% url 'events:delete_event' event.pk %}">
                  {% csrf_token %}
                  <button class="btn btn-danger float-right" type="submit">{% trans 'Delete' %}</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      {% empty %}
        <h4>{% trans 'There are no events registered.'%}</h4>
      {% endfor %}
    </div>
  </div>

{% endblock %}