config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    url(r'', include('drdown.core.urls', namespace='core')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('drdown.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^forum/', include('drdown.forum.urls', namespace='forum')),
    url(r'^careline/', include('drdown.careline.urls', namespace='careline')),
    url(r'^medicalrecords/', include('drdown.medicalrecords.urls', namespace='medicalrecords')),
    url(r'^appointments/', include('drdown.appointments.urls', namespace='appointments')),
    url(r'^events/', include('drdown.events.urls', namespace='events')),
    url(r'^notifications/', include('drdown.notifications.urls', namespace='notifications')),
    url(r'^i18n/', include('django.conf.urls.i18n')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

drdown/medicalrecords/urls.py
from django.conf.urls import url
from drdown.medicalrecords.forms.exam_forms import ExamForm
from drdown.medicalrecords.forms.medicalrecords_forms import MedicalRecordForm
from drdown.medicalrecords.forms.static_data_forms import StaticDataForm
from drdown.medicalrecords.forms.medicines_forms import MedicineForm
from drdown.medicalrecords.forms.complaint_forms import ComplaintForm
from drdown.medicalrecords.forms.risk_forms import RiskForm
from drdown.medicalrecords.views import (
    view_medical_record, view_static_data,
    view_medicines, view_complaint, view_exams,
    view_pdf, view_risk, view_curves,
)

app_name = 'medicalrecords'
urlpatterns = [
    url(
        regex=r'list/(?P<username>[\w.@+-]+)/$',
        view=view_medical_record.MedicalRecordsList.as_view(),
        name='list_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new/$',
        view=view_medical_record.MedicalRecordsCreateView.as_view(
            form_class=MedicalRecordForm),
        name='create_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-static-data/$',
        view=view_static_data.StaticDataCreateView.as_view(
            form_class=StaticDataForm),
        name='create_static_data_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-medicine/$',
        view=view_medicines.MedicinesCreateView.as_view(
            form_class=MedicineForm),
        name='create_medicine_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-complaint/$',
        view=view_complaint.ComplaintCreateView.as_view(
            form_class=ComplaintForm),
        name='create_complaint_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-exam/$',
        view=view_exams.ExamCreateView.as_view(
            form_class=ExamForm),
        name='create_exam_medicalrecords'
    ),

    url(
        regex=r'^(?P<username>[\w.@+-]+)/update-static-data/$',
        view=view_static_data.StaticDataUpdateView.as_view(
            form_class=StaticDataForm),
        name='update_static_data_medicalrecords'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/new-medicine/$',
        view=view_medicines.MedicinesCreateView.as_view(
            form_class=MedicineForm),
        name='create_medicine'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/update-medicine/(?P<pk>\d+)/$',
        view=view_medicines.MedicinesUpdateView.as_view(
            form_class=MedicineForm),
        name='update_medicine'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/risk/edit/$',
        view=view_risk.RiskUpdateView.as_view(),
        name='update_risk'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/pdf/$',
        view=view_pdf.PDFView.as_view(),
        name='pdf'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/curves/create-height/$',
        view=view_curves.CurvesCreateView.as_view(),
        name='create_curve'
    ),
    url(
        regex=r'(?P<username>[\w.@+-]+)/curves/update-height/(?P<pk>\d+)/$',
        view=view_curves.CurvesUpdateView.as_view(),
        name='update_curve'
    ),
    url(
        regex=r'curves/ajax/$',
        view=view_curves.CurveDataParser.as_view(),
        name='curve_ajax'
    ),
]

drdown/medicalrecords/models/model_complaint.py
from django.db import models
from drdown.users.models.model_health_team import HealthTeam
from drdown.users.models.model_patient import Patient
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core.exceptions import ValidationError


class Complaint(models.Model):

    created_at = models.DateTimeField(
        _('Created at'),
        help_text=_('Date of creation'),
        auto_now_add=True
    )

    complaint_day = models.DateField(
        _('Day of complaint'),
    )

    complaint_time = models.TimeField(
        _('Time of complaint'),
        null=True,
        blank=True
    )

    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        verbose_name=_('Patient')
    )

    description = models.TextField(
        _('Description'),
        help_text=_('Description of the complaint'),
        max_length=4000
    )

    author = models.ForeignKey(
        HealthTeam,
        on_delete=models.CASCADE,
        verbose_name=_("Author")
    )

    class Meta:
        verbose_name = _("Complaint")
        verbose_name_plural = _("Complaints")

    def clean(self, *args, **kwargs):
        if self.complaint_day:
            if timezone.localdate().isoformat() < str(self.complaint_day):
                raise ValidationError(
                    {'complaint_day':
                        _("The complaint cannot be in the future!")}
                )

        return super(Complaint, self).clean()

    def __str__(self):
        return self.patient.user.get_username() + " -  Comptaint ID: " + \
               str(self.id)

drdown/medicalrecords/models/model_exams.py
from django.db import models
from drdown.users.models.model_patient import Patient
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.core.exceptions import ValidationError


class Exam(models.Model):

    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        verbose_name=_('Patient')
    )

    file = models.FileField(
        upload_to='media/medicalrecords/exams',
        verbose_name=_('Exam'),
        help_text=_('Exam file'),
    )

    day = models.DateTimeField(
        _('Exam day'),
        help_text=_('Day the exam was performed'),
    )

    CATEGORIES = (
        (None, _("Select a category...")),
        (0, _("Others")),
        (1, _('Structured Physical Exam')),
        (2, _('Vision Exam')),
        (3, _('Ear Exam')),
        (4, _('Hearth Exam')),
        (5, _('Muscle skeletal system Exam')),
        (6, _('Nervous system Exam')),
        (7, _('Blood Exam')),
        (8, _('Bone Densitometry')),
        (9, _('Biopsy')),
        (10, _('Endoscopy')),
        (11, _('Echocardiogram')),
        (12, _('Map and Holter')),
        (13, _('Bioimpedance')),
        (14, _('Neurological examinations')),
        (15, _('Urine Analysis')),
        (16, _('Stool Examination')),
    )

    category = models.IntegerField(
        _('Category'),
        choices=CATEGORIES,
        help_text=_("Please, insert the category of the exam"),
        null=True,
        blank=False,
    )

    observations = models.CharField(
        _('Observations'),
        max_length=200,
        blank=True,
        default=""
    )

    def __str__(self):
        return (
            self.patient.user.get_username() +
            " - " + self.get_category_display()
        )

    def clean(self, *args, **kwargs):
        if self.day:
            if timezone.now() < self.day:
                raise ValidationError(
                    {'day':
                        _("The exam cannot be in the future!")}
                )

        return super(Exam, self).clean()

    class Meta:
        verbose_name = _("Exam")
        verbose_name_plural = _("Exams")

drdown/medicalrecords/models/model_medical_record.py
from django.db import models
from drdown.users.models.model_health_team import HealthTeam
from drdown.users.models.model_patient import Patient
from django.utils.translation import ugettext_lazy as _
from datetime import datetime
from django.core.exceptions import ValidationError


class MedicalRecord(models.Model):

    document = models.FileField(upload_to='media/', blank=True)

    day = models.DateTimeField(
        _('Created at'),
        help_text=_('Patient Care Day'),
        auto_now=True
    )

    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        verbose_name=_('Patient')
    )

    message = models.TextField(
        _('Message'),
        help_text=_('Message of medical records'),
        max_length=4000
    )

    author = models.ForeignKey(
        HealthTeam,
        on_delete=models.CASCADE,
        verbose_name=_("Author")
    )

    def __str__(self):
        return self.patient.user.get_username()

    class Meta:
        verbose_name = _("Medical Record")
        verbose_name_plural = _("Medical Records")

drdown/medicalrecords/models/model_medicines.py
from django.db import models
from drdown.users.models.model_health_team import HealthTeam
from drdown.users.models.model_patient import Patient
from django.utils.translation import ugettext_lazy as _


class Medicine(models.Model):

    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        verbose_name=_('Patient')
    )

    medicine_name = models.CharField(
        max_length=100,
        verbose_name=_('Medicine Name')
    )

    medicine_dosage = models.CharField(
        max_length=100,
        verbose_name=_('Medicine dosage')
    )

    medicine_in_use = models.BooleanField(
        verbose_name=_('In use?'),
        help_text=_('Does the patient still use this medication?'),
        default=True
    )

    medicine_use_interval = models.CharField(
        _('Time between uses'),
        max_length=50,
        default=""
    )

    author = models.ForeignKey(
        HealthTeam,
        on_delete=models.CASCADE,
        verbose_name=_("Author")
    )

    def __str__(self):
        return self.patient.user.get_username() + " - " + self.medicine_name

    class Meta:
        verbose_name = _("Patient Medicine")

drdown/medicalrecords/forms/exam_forms.py
from drdown.medicalrecords.models.model_exams import Exam
from django import forms


class ExamForm(forms.ModelForm):

    class Meta:
        model = Exam
        fields = ["file", "day", "category", "observations"]
        widgets = {
            'day': forms.DateInput(attrs={'type': 'date'})
        }

drdown/medicalrecords/views/view_complaint.py
from drdown.users.models.model_health_team import HealthTeam
from ..models.model_complaint import Complaint
from drdown.users.models.model_user import User
from drdown.users.models.model_patient import Patient
from django.views.generic import CreateView,  UpdateView
from django.urls import reverse_lazy
from ..forms.complaint_forms import ComplaintForm
from ..views.views_base import BaseViewForm, BaseViewUrl, BaseViewPermissions


class ComplaintCreateView(BaseViewForm, BaseViewUrl,
                          BaseViewPermissions, CreateView):
    model = Complaint
    form_class = ComplaintForm
    template_name = 'medicalrecords/medicalrecord_complaint_form.html'


class ComplaintUpdateView(BaseViewUrl, UpdateView):
    model = Complaint
    form_class = ComplaintForm
    template_name = 'medicalrecords/medicalrecord_complaint_form.html'

drdown/medicalrecords/views/view_exams.py
from drdown.users.models.model_health_team import HealthTeam
from ..models.model_exams import Exam
from drdown.users.models.model_user import User
from drdown.users.models.model_patient import Patient
from django.views.generic import CreateView,  UpdateView
from django.urls import reverse_lazy
from ..forms.exam_forms import ExamForm
from ..views.views_base import BaseViewForm, BaseViewUrl, BaseViewPermissions


class ExamCreateView(BaseViewForm, BaseViewUrl, BaseViewPermissions,
                     CreateView):
    model = Exam
    form_class = ExamForm
    template_name = 'medicalrecords/medicalrecord_exam_form.html'


class ExamUpdateView(BaseViewUrl, UpdateView):
    model = Exam
    form_class = ExamForm
    template_name = 'medicalrecords/medicalrecord_exam_form.html'

drdown/medicalrecords/views/view_medical_record.py
from drdown.users.models.model_health_team import HealthTeam
from ..models.model_medical_record import MedicalRecord
from ..models.model_static_data import StaticData
from ..models.model_medicines import Medicine
from ..models.model_exams import Exam
from ..models.model_risk import Risk
from ..models.model_complaint import Complaint
from drdown.users.models.model_user import User
from drdown.users.models.model_patient import Patient
from django.views.generic import CreateView, DeleteView, UpdateView, ListView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import UserPassesTestMixin
from search_views.filters import BaseFilter
from ..forms.medicalrecords_forms import MedicalRecordForm
from ..views.views_base import BaseViewForm, BaseViewUrl


class MedicalRecordsFilter(BaseFilter):
    search_fields = {
        'list_patient': ['id']
    }


class MedicalRecordsList(UserPassesTestMixin, ListView):
    model = MedicalRecord
    template_name = "medicalrecords/medicalrecord_list.html"
    slug_url_kwarg = 'username'
    slug_field = 'patient__user__username'
    ordering = ['-day']

    def test_func(self):
        return hasattr(self.request.user, 'healthteam') or \
               hasattr(self.request.user, 'employee') or \
               self.request.user.username == self.kwargs.get('username') or \
               (hasattr(self.request.user, 'responsible') and
                self.request.user.responsible.patient_set.filter(
                    user__username=self.kwargs.get('username')))

    def get_login_url(self):
        if self.request.user.is_authenticated:
            # redirect if user is not a HealthTeam or the patient itself
            login_MedicalRecordsList_url = reverse_lazy(
                viewname='users:detail',
                kwargs={'username': self.request.user.username}
            )
            return login_MedicalRecordsList_url
        login_MedicalRecordsList_url = reverse_lazy('account_login')
        return login_MedicalRecordsList_url

    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)

        patient = Patient.objects.get(
            user__username=self.kwargs.get('username')
        )

        staticdata = StaticData.objects.filter(patient=patient)
        medicines = Medicine.objects.filter(patient=patient)
        complaints = Complaint.objects.filter(patient=patient)
        risk = Risk.objects.filter(patient=patient)

        curves = patient.curves_set.all().order_by('age')

        context['complaints'] = complaints
        context['curves'] = curves
        context['medicines'] = medicines
        context['staticdata'] = staticdata

        context['risk_priority_speech_theraphy'] = \
            patient.risk.get_priority_speech_theraphy_display()
        context['risk_priority_general_practitioner'] = \
            patient.risk.get_priority_general_practitioner_display()
        context['risk_priority_pediatrics'] = \
            patient.risk.get_priority_pediatrics_display()
        context['risk_priority_neurology'] = \
            patient.risk.get_priority_neurology_display()
        context['risk_priority_cardiology'] = \
            patient.risk.get_priority_cardiology_display()
        context['risk_priority_physiotherapy'] = \
            patient.risk.get_priority_physiotherapy_display()
        context['risk_priority_psychology'] = \
            patient.risk.get_priority_psychology_display()

        context['medicalrecordlist'] = context['object_list'].filter(
            patient=patient
        )

        context['related_patient'] = patient

        exams = Exam.objects.filter(patient=patient)
        context['exams'] = exams

        category_dict = {}

        for category in Exam.CATEGORIES:
            query = Exam.objects.filter(
                patient=patient,
                category=category[0]
            )

            if query.exists():
                category_dict[category[1]] = query

        context['exams_categories'] = category_dict

        return context


class MedicalRecordsCreateView(BaseViewUrl, BaseViewForm, CreateView):
    model = MedicalRecord
    form_class = MedicalRecordForm
    template_name = 'medicalrecords/medicalrecord_form.html'

drdown/medicalrecords/templates/medicalrecords/medicalrecord_exam_form.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}{% trans 'New Medical Record' %}{% endblock %}

{% block css %}
{{block.super}}
<link href="{% static 'medicalrecords/css/medicalrecords.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="container">

    <div class="row">
      <div class="col">
          <h2>{% trans 'Add Exam' %}</h2>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <form method="post" enctype="multipart/form-data"action="#menu2">
          {% csrf_token %}

            <div class="formgroup row my-2  border rounded">

              {% if form.file.errors %}
                <div class="col-11 alert alert-danger mx-auto mt-2" role="alert">
                  {{ form.file.errors }}
                </div>
               {% endif %}

               <div class="col-12">
                 {{ form.file.label_tag }}
               </div>

               <div class="col-12 mb-2">
                  {{ form.file }}
              </div>
             </div>

            <div class="formgroup row my-2  border rounded">

              {% if form.day.errors %}
                <div class="col-11 alert alert-danger mx-auto mt-2" role="alert">
                  {{ form.day.errors }}
                </div>
               {% endif %}

               <div class="col-12">
                 {{ form.day.label_tag }}
               </div>

               <div class="col-12">
                  <input class="form-control mb-2" type="date"
                         name="day"
                         required="" id="id_day"
                  >
              </div>
             </div>

              <div class="formgroup row my-2  border rounded">
               {% if form.category.errors %}
                  <div class="col-11 alert alert-danger mx-auto mt-2" role="alert">
                    {{ form.category.errors }}
                  </div>
               {% endif %}

               <div class="col-12">
                 {{ form.category.label_tag }}
               </div>

               <div class="col-12 mb-2">
                 <select name="category" class="select form-control" required="" id="id_category">
                   <option value="">{% trans "Select a category..."%}</option>
                   <option value="0">{%trans "Others"%}</option>
                   <option value="1">{%trans 'Structured Physical Exam'%}</option>
                   <option value="2">{%trans 'Vision Exam'%}</option>
                    <option value="3">{%trans 'Ear Exam' %}</option>
                    <option value="4">{%trans 'Hearth Exam' %}</option>
                    <option value="5">{%trans 'Muscle skeletal system Exam' %}</option>
                    <option value="6">{%trans 'Nervous system Exam' %}</option>
                    <option value="7">{%trans 'Blood Exam' %}</option>
                    <option value="8">{%trans 'Bone Densitometry' %}</option>
                    <option value="9">{%trans 'Biopsy' %}</option>
                    <option value="10">{%trans 'Endoscopy' %}</option>
                    <option value="11">{%trans 'Echocardiogram' %}</option>
                    <option value="12">{%trans 'Map and Holter' %}</option>
                    <option value="13">{%trans 'Bioimpedance' %}</option>
                    <option value="14">{%trans 'Neurological examinations' %}</option>
                    <option value="15">{%trans 'Urine Analysis' %}</option>
                    <option value="16">{%trans 'Stool Examination' %}</option>
                  </select>
               </div>
             </div>

             <div class="formgroup row my-2  border rounded">
               {% if form.observations.errors %}
                <div class="col-12 alert alert-danger" role="alert">
                  {{ form.observations.errors }}
                </div>
               {% endif %}

               <div class="col-12">
                 {{ form.observations.label_tag }}
               </div>

               <div class="col-12">
                 <input class="form-control mb-2" type="text"
                         name="observations" maxlength="100"
                         id="id_observations"
                  >
               </div>
             </div>

            <div class="row float-right mr-2">
              <a href="{% url 'medicalrecords:list_medicalrecords' view.kwargs.username  %}#menu2" class="btn btn-danger my-3 mx-1" >{% trans "Cancel" %}</a>
              <button type="submit" class="btn btn-success my-3 mx-1">{% trans 'Save' %}</button>
            </div>
        </form>

      </div>
    </div>

  </div>

{% endblock %}

drdown/medicalrecords/templates/medicalrecords/medicalrecord_medicine_form.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}{% trans 'New Medical Record' %}{% endblock %}

{% block css %}
{{block.super}}
<link href="{% static 'medicalrecords/css/medicalrecords.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="container">

    <div class="row">
      <div class="col">
        <h2>{% trans 'Prescription' %}</h2>
      </div>
    </div>

    <div class="row">
      <div class="col">

        <form method="post" enctype="multipart/form-data" action="#menu3">

          {% csrf_token %}
            <div class="formgroup row my-2  border rounded">
                <div class="col fieldWrapper my-2">
                    {% if form.medicine_name.errors %}
                        <div class="col">
                            {{ form.medicine_name.errors }}
                        </div>
                    {% endif %}

                    <div class="col">
                        {{ form.medicine_name.label_tag }}
                    </div>

                    <div class="col">
                      {% if object.medicine_name %}
                        <input class="form-control mb-2" type="text"
                               name="medicine_name" maxlength="100"
                               required="" id="id_medicine_name"
                               value="{{ object.medicine_name }}"
                        >
                      {% else %}
                         <input class="form-control mb-2" type="text"
                               name="medicine_name" maxlength="100"
                               required="" id="id_medicine_name"
                               placeholder="{% trans 'Enter your medication name here' %}"
                        >
                      {% endif %}
                    </div>
                {% if field.help_text %}
                  <font size="2" class="ml-3">{{ form.medicine_name.help_text|safe }}</font>
                {% endif %}
                </div>
            </div>

            <div class="formgroup row my-2  border rounded">
                <div class="col fieldWrapper my-2">
                    {% if form.medicine_dosage.errors %}
                        <div class="col">
                            {{ form.medicine_dosage.errors }}
                        </div>
                    {% endif %}

                    <div class="col">
                        {{ form.medicine_dosage.label_tag }}
                    </div>

                    <div class="col">
                      {% if object.medicine_dosage %}
                        <input class="form-control mb-2" type="text"
                               name="medicine_dosage" maxlength="100"
                               required="" id="id_medicine_dosage"
                               value="{{ object.medicine_dosage }}"
                        >
                      {% else %}
                        <input class="form-control mb-2" type="text"
                               name="medicine_dosage" maxlength="100"
                               required="" id="id_medicine_dosage"
                               placeholder="{% trans 'Enter your medication dosage here' %}"
                        >
                      {% endif %}
                    </div>
                {% if field.help_text %}
                  <font size="2" class="ml-3">{{ form.medicine_dosage.help_text|safe }}</font>
                {% endif %}
                </div>
            </div>

            <div class="formgroup row my-2  border rounded">
                <div class="col fieldWrapper my-2">
                    {% if form.medicine_use_interval.errors %}
                        <div class="col">
                            {{ form.medicine_use_interval.errors }}
                        </div>
                    {% endif %}

                    <div class="col">
                        {{ form.medicine_use_interval.label_tag }}
                    </div>

                    <div class="col">
                      {% if object.medicine_use_interval %}
                        <input class="form-control mb-2" type="text"
                               name="medicine_use_interval" maxlength="50"
                               required="" id="id_medicine_use_interval"
                               value="{{ object.medicine_use_interval }}"

                        >
                      {% else %}
                        <input class="form-control mb-2" type="text"
                               name="medicine_use_interval" maxlength="50"
                               required="" id="id_medicine_use_interval"
                               placeholder="{% trans 'Enter your medication use interval here' %}"

                        >
                      {% endif %}
                    </div>
                {% if field.help_text %}
                  <font size="2" class="ml-3">{{ form.medicine_use_interval.help_text|safe }}</font>
                {% endif %}
                </div>
            </div>


            <div class="formgroup row my-2  border rounded">
                <div class="col fieldWrapper my-2">
                    {% if form.medicine_in_use.errors %}
                        <div class="col">
                            {{ form.medicine_in_use.errors }}
                        </div>
                    {% endif %}

                    <div class="col">
                        {{ form.medicine_in_use.label_tag }}
                    </div>

                    <div class="col">
                        {{ form.medicine_in_use }}
                    </div>
                {% if field.help_text %}
                  <font size="2" class="ml-3">{{ form.medicine_in_use.help_text|safe }}</font>
                {% endif %}
                </div>
            </div>

          <div class="row float-right mr-2">
            <a href="{% url 'medicalrecords:list_medicalrecords' view.kwargs.username  %}#menu3" class="btn btn-danger my-3 mx-1" >{% trans "Cancel" %}</a>
            <button type="submit" class="btn btn-success my-3 mx-1">{% trans 'Save' %}</button>
          </div>
        </form>

      </div>
    </div>

  </div>

{% endblock %}

drdown/medicalrecords/templates/medicalrecords/medicines.html
{% load static i18n %}

    <div class="row mb-5">
      <div class="col">
        <h3 >{% trans "Patient prescription" %}</h3>
      </div>
      <div class="col-auto">
        {% if request.user.healthteam %}
          <a href="{% url 'medicalrecords:create_medicine'  view.kwargs.username %}" class="btn btn-success float-right" >{% trans "Add" %}</a>
        {% endif %}
      </div>
    </div>
    <div class="row mb-5">
      <div class="col">
        {% if medicines %}
          <div class="table-responsive">
            <table class="table table-hover table-sm table-bordered">
              <thead class="btn-secondary">
                <tr>
                  {% if request.user.healthteam or request.user.employee %}
                    <th class="col-auto" scope="col">{% trans 'Medicine' %}</th>
                  {% endif %}
                  <th class="col-auto" scope="col">{% trans 'Name of medicine' %}</th>
                  <th class="col-auto" scope="col">{% trans 'Dosage' %}</th>
                  <th class="col-auto" scope="col">{% trans 'Time between uses' %}</th>
                  <th class="col-auto" scope="col">{% trans 'In use?' %}</th>
                </tr>
              </thead>
              <tbody>
                {% for medicine in medicines %}
                  <tr>
                    {% if request.user.healthteam %}
                    <th scope="row">
                      <a href="{% url 'medicalrecords:update_medicine' view.kwargs.username medicine.pk %}" class="btn btn-secondary" >{% trans "Edit" %}</a>
                    </th>
                    {% endif %}
                    <td style="vertical-align:middle">{{medicine.medicine_name}}</td>
                    <td style="vertical-align:middle">{{medicine.medicine_dosage}}</td>
                    <td style="vertical-align:middle">{{medicine.medicine_use_interval}}</td>
                    <td style="vertical-align:middle">
                        <input type="checkbox" disabled {% if  medicine.medicine_in_use %} checked {% endif %} >
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        {% else %}
          <h4>{% trans "There are no prescriptions registered for this patient."%}</h4>
        {% endif %}
      </div>
    </div>