config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views

urlpatterns = [
    url(r'', include('drdown.core.urls', namespace='core')),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('drdown.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^forum/', include('drdown.forum.urls', namespace='forum')),
    url(r'^careline/', include('drdown.careline.urls', namespace='careline')),
    url(r'^medicalrecords/', include('drdown.medicalrecords.urls', namespace='medicalrecords')),
    url(r'^appointments/', include('drdown.appointments.urls', namespace='appointments')),
    url(r'^events/', include('drdown.events.urls', namespace='events')),
    url(r'^notifications/', include('drdown.notifications.urls', namespace='notifications')),
    url(r'^i18n/', include('django.conf.urls.i18n')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

drdown/appointments/urls.py
from django.conf.urls import url
from drdown.appointments.views.view_appointment import (
    AppointmentListView,
    AppointmentCreateView,
    AppointmentUpdateView,
    AppointmentMonthArchiveView,
    AppointmentUpdateStatusView,
    AppointmentFromRequestCreateView,
)
from drdown.appointments.views.view_request import (
    RequestListView,
    RequestCreateView,
    RequestUpdateView,
    RequestDeleteView,
    RequestUpdateStatusView,
    RequestAfterResultDeleteView,
    load_doctors
)


app_name = 'appointments'
urlpatterns = [
    url(
        regex=r'^$',
        view=AppointmentListView.as_view(),
        name='list_appointments'
    ),
    url(
        regex=r'^request/new/$',
        view=RequestCreateView.as_view(),
        name='create_request'
    ),
    url(
        regex=r'^requests/$',
        view=RequestListView.as_view(),
        name='list_requests'
    ),
    url(
        regex=r'^request/update/(?P<request_pk>\d+)/$',
        view=RequestUpdateView.as_view(),
        name='update_request'
    ),
    url(
        regex=r'^request/delete/(?P<request_pk>\d+)/$',
        view=RequestDeleteView.as_view(),
        name='delete_request'
    ),
    url(
        regex=r'^request/result/delete/(?P<request_pk>\d+)/$',
        view=RequestAfterResultDeleteView.as_view(),
        name='delete_request_after_result'
    ),
    url(
        regex=r'^new/$',
        view=AppointmentCreateView.as_view(),
        name='create_appointment'
    ),
    url(
        regex=r'^new/(?P<request_pk>\d+)/$',
        view=AppointmentFromRequestCreateView.as_view(),
        name='create_from_request'
    ),
    url(
        regex=r'^(?P<year>\d{4})/(?P<month>\d+)/$',
        view=AppointmentMonthArchiveView.as_view(month_format='%m'),
        name="archive_month"
    ),
    url(
        regex=r'^update/(?P<appointment_pk>\d+)/$',
        view=AppointmentUpdateView.as_view(),
        name='update_appointment'
    ),
    url(
        regex=r'^cancel/(?P<appointment_pk>\d+)/$',
        view=AppointmentUpdateStatusView.as_view(),
        name='update_status_appointment'
    ),
    url(
        regex=r'^request/cancel/(?P<request_pk>\d+)/$',
        view=RequestUpdateStatusView.as_view(),
        name='update_status_request'
    ),
    url(
        regex=r'^ajax/load-doctors/$',
        view=load_doctors,
        name='ajax_load_doctors'
    ),

]

drdown/appointments/models/model_appointment.py
from django.db import models
from drdown.users.models.model_health_team import HealthTeam
from drdown.users.models.model_patient import Patient
from django.utils.translation import ugettext_lazy as _


class Appointment(models.Model):

    date = models.DateField(
        _('Date'),
        help_text=_('Date of appointment'),
        max_length=50
    )

    time = models.TimeField(
        _('Time'),
        help_text=_('Time of appointment'),
        max_length=50
    )

    SPEECH_THERAPHY = "Speech Therapy"
    PSYCHOLOGY = "Psychology"
    PHYSIOTHERAPY = "Physiotherapy"
    OCCUPATIONAL_THERAPY = "Occupational Therapy"
    CARDIOLOGY = "Cardiology"
    NEUROLOGY = "Neurology"
    PEDIATRICS = "Pediatrics"
    GENERAL_PRACTITIONER = "General Practitioner"

    SPECIALITY_APPOINTMENT_CHOICES = (
        (SPEECH_THERAPHY, _('Speech Therapy')),
        (PSYCHOLOGY, _('Psychology')),
        (PHYSIOTHERAPY, _('Physiotherapy')),
        (OCCUPATIONAL_THERAPY, _('Occupational Therapy')),
        (CARDIOLOGY, _('Cardiology')),
        (NEUROLOGY, _('Neurology')),
        (PEDIATRICS, _('Pediatrics')),
        (GENERAL_PRACTITIONER, _('General Practitioner')),
    )

    speciality = models.CharField(
        _('Speciality'),
        choices=SPECIALITY_APPOINTMENT_CHOICES,
        help_text=_("Speciality of appointment"),
        max_length=30
    )

    doctor = models.ForeignKey(
        HealthTeam,
        on_delete=models.CASCADE,
        verbose_name=_('Doctor'),
        related_name='appointments',
    )

    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        verbose_name=_('Patient'),
        related_name='appointments',
    )

    SCHEDULED = 'Scheduled'
    CANCELED = 'Canceled'

    STATUS_CHOICES = (
        (SCHEDULED, _('Scheduled')),
        (CANCELED, _('Canceled')),
    )

    status = models.CharField(
        _('Status'),
        choices=STATUS_CHOICES,
        help_text=_("Is this appointment still scheduled?"),
        default=SCHEDULED,
        max_length=20,
        editable=False,
    )

    def __str__(self):
        return _('Appointment of ') + self.patient.user.name

    class Meta:
        verbose_name = _("Appointment")
        verbose_name_plural = _("Appointments")

drdown/appointments/models/model_request.py
from django.db import models
from drdown.users.models.model_health_team import HealthTeam
from drdown.users.models.model_patient import Patient
from django.utils.translation import ugettext_lazy as _
from drdown.notifications.utils import mail


class AppointmentRequest(models.Model):

    MORNING = 'M'
    AFTERNOON = 'A'

    SHIFT_CHOICES = (
        (MORNING, _('Morning')),
        (AFTERNOON, _('Afternoon')),
    )

    shift = models.CharField(
        _('Shift'),
        choices=SHIFT_CHOICES,
        help_text=_('Preferred shift'),
        max_length=10
    )

    SUNDAY = 'Sunday'
    MONDAY = 'Monday'
    TUESDAY = 'Tuesday'
    WEDNESDAY = 'Wednesday'
    THURSDAY = 'Thursday'
    FRIDAY = 'Friday'
    SATURDAY = 'Saturday'

    DAYS_CHOICES = (
        (SUNDAY, _('Sunday')),
        (MONDAY, _('Monday')),
        (TUESDAY, _('Tuesday')),
        (WEDNESDAY, _('Wednesday')),
        (THURSDAY, _('Thursday')),
        (FRIDAY, _('Friday')),
        (SATURDAY, _('Saturday')),
    )

    day = models.CharField(
        _('Day of the week'),
        choices=DAYS_CHOICES,
        help_text=_("Preferred day of the week. " +
                    "It is not guaranteed that the appointment will be " +
                    "marked on the preferred day."),
        max_length=10
    )

    motive = models.TextField(
        _('Motive'),
        help_text=_('Why are you requesting an appointment?'),
        max_length=500,
        blank=True,
    )

    observation = models.TextField(
        _('Observation'),
        help_text=_('Why was it scheduled/declined?'),
        max_length=500,
        blank=True,
    )

    SPEECH_THERAPHY = "Speech Therapy"
    PSYCHOLOGY = "Psychology"
    PHYSIOTHERAPY = "Physiotherapy"
    OCCUPATIONAL_THERAPY = "Occupational Therapy"
    CARDIOLOGY = "Cardiology"
    NEUROLOGY = "Neurology"
    PEDIATRICS = "Pediatrics"
    GENERAL_PRACTITIONER = "General Practitioner"

    SPECIALITY_REQUEST_CHOICES = (
        (SPEECH_THERAPHY, _('Speech Therapy')),
        (PSYCHOLOGY, _('Psychology')),
        (PHYSIOTHERAPY, _('Physiotherapy')),
        (OCCUPATIONAL_THERAPY, _('Occupational Therapy')),
        (CARDIOLOGY, _('Cardiology')),
        (NEUROLOGY, _('Neurology')),
        (PEDIATRICS, _('Pediatrics')),
        (GENERAL_PRACTITIONER, _('General Practitioner')),
    )

    speciality = models.CharField(
        _('Speciality'),
        choices=SPECIALITY_REQUEST_CHOICES,
        help_text=_("Desired specialty"),
        max_length=30
    )

    doctor = models.ForeignKey(
        HealthTeam,
        on_delete=models.CASCADE,
        verbose_name=_('Doctor'),
        related_name='requests',
        help_text=_("Preferred doctor. " +
                    "It is not guaranteed that the appointment will be " +
                    "scheduled with the doctor preferred."),
        blank=True,
        null=True,
    )

    patient = models.ForeignKey(
        Patient,
        on_delete=models.CASCADE,
        verbose_name=_('Patient'),
        related_name='requests',
    )

    SCHEDULED = 'Scheduled'
    PENDING = _('Pending')
    DECLINED = 'Declined'

    STATUS_CHOICES = (
        (SCHEDULED, _('Scheduled')),
        (DECLINED, _('Declined')),
    )

    status = models.CharField(
        _('Status'),
        help_text=_("Was the request accepted?"),
        choices=STATUS_CHOICES,
        default=PENDING,
        max_length=20,
        editable=False,
    )

    RISKS = (
      (5, _('Not urgent')),
      (4, _('Not very urgent')),
      (3, _('Urgent')),
      (2, _('Very urgent')),
      (1, _('Emerging')),
    )
    risk = models.IntegerField(
      _('Risk'),
      choices=RISKS,
      default=5,
    )

    def __str__(self):
        return _('Appointment request of ') + self.patient.user.name

    def save(self, *args, **kwargs):
        if self.status == AppointmentRequest.SCHEDULED:
            mail.send_appointment_sucess_message(self.patient, self)
        elif self.status == AppointmentRequest.DECLINED:
            mail.send_appointment_cancel_message(self.patient, self)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = _("Request")
        verbose_name_plural = _("Requests")

drdown/appointments/forms/appointments_form.py
from drdown.appointments.models.model_appointment import Appointment
from django import forms
from drdown.users.models.model_health_team import HealthTeam
from drdown.users.models.model_patient import Patient
from django.utils.translation import ugettext_lazy as _


class AppointmentSearchForm(forms.Form):
    search_speciality = forms.ChoiceField(
        required=False,
        label=_('Speciality'),
    )

    search_date = forms.DateField(
        required=False,
        label=_('Date'),
        widget=forms.SelectDateWidget(
            empty_label=(_("Year"), _("Month"), _("Day")),
        )
    )

    search_name = forms.CharField(
       required=False,
       label=_('Name'),
    )

drdown/appointments/views/view_request.py
from django.shortcuts import render
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import UpdateView
from django.views.generic import DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from search_views.search import SearchListView
from drdown.users.models.model_patient import Patient
from drdown.users.models.model_health_team import HealthTeam
from search_views.filters import BaseFilter
from drdown.appointments.models import AppointmentRequest
from drdown.appointments.forms.requests_form import RequestSearchForm, \
    RequestForm


class RequestFilter(LoginRequiredMixin, BaseFilter):
    search_fields = {
        'search_speciality': ['speciality'],
        'search_name': ['doctor__user__name', 'patient__user__name'],
    }


class RequestListView(LoginRequiredMixin, SearchListView):
    model = AppointmentRequest
    template_name = 'appointments/request_list.html'
    form_class = RequestSearchForm
    filter_class = RequestFilter
    paginate_by = 10

    def prepare_queryset(self, request):
        user = request.user
        if hasattr(user, 'patient'):
            queryset = AppointmentRequest.objects.filter(
                patient=user.patient
            ).order_by('id')
        elif hasattr(user, 'responsible'):
            queryset = AppointmentRequest.objects.filter(
                patient__in=user.responsible.patient_set.all()
            ).order_by('id')
        elif hasattr(user, 'employee'):
            queryset = AppointmentRequest.objects.filter(
                ).order_by('risk', 'id')
        else:
            queryset = AppointmentRequest.objects.none()
        return queryset

    def get_queryset(self):
        return self.prepare_queryset(self.request)


class RequestCreateView(LoginRequiredMixin, CreateView):
    model = AppointmentRequest
    template_name = 'appointments/request_form.html'
    form_class = RequestForm
    success_url = reverse_lazy(
            viewname='appointments:list_requests',
    )

    def form_valid(self, form):
        speciality = form.instance.speciality
        risk = 5

        if speciality == AppointmentRequest.CARDIOLOGY:
            risk = form.instance.patient.risk.priority_cardiology

        if speciality == AppointmentRequest.NEUROLOGY:
            risk = form.instance.patient.risk.priority_neurology

        if speciality == AppointmentRequest.PEDIATRICS:
            risk = form.instance.patient.risk.priority_pediatrics

        if speciality == AppointmentRequest.SPEECH_THERAPHY:
            risk = form.instance.patient.risk.priority_speech_theraphy

        if speciality == AppointmentRequest.PHYSIOTHERAPY:
            risk = form.instance.patient.risk.priority_physiotherapy

        if speciality == AppointmentRequest.PSYCHOLOGY:
            risk = form.instance.patient.risk.priority_psychology

        if speciality == AppointmentRequest.GENERAL_PRACTITIONER:
            risk = form.instance.patient.risk.priority_general_practitioner

        form.instance.risk = risk

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(RequestCreateView, self).get_context_data(**kwargs)

        context['health_team'] = HealthTeam.objects.all()
        if hasattr(self.request.user, 'patient'):
            context['patients'] = Patient.objects.filter(
                user=self.request.user)
        elif hasattr(self.request.user, 'responsible'):
            context['patients'] = \
                self.request.user.responsible.patient_set.all()
        return context


def load_doctors(request):
    speciality = request.GET.get('speciality')
    doctors = HealthTeam.objects.filter(
        speciality=speciality
    ).order_by('user__name')
    return render(request,
                  'appointments/doctors_dropdown_list_options.html',
                  {'doctors': doctors}
                  )


class RequestUpdateView(LoginRequiredMixin, UpdateView):
    model = AppointmentRequest
    template_name = 'appointments/request_form.html'
    fields = [
        'speciality',
        'doctor',
        'patient',
        'shift',
        'day',
        'motive',
    ]
    success_url = reverse_lazy(
            viewname='appointments:list_requests',
    )
    pk_url_kwarg = 'request_pk'


class RequestDeleteView(LoginRequiredMixin, DeleteView):
    model = AppointmentRequest
    template_name = 'appointments/request_confirm_delete.html'
    success_url = reverse_lazy(
            viewname='appointments:list_requests',
    )
    pk_url_kwarg = 'request_pk'


class RequestUpdateStatusView(LoginRequiredMixin, UpdateView):
    model = AppointmentRequest
    template_name = 'appointments/request_confirm_cancel.html'
    fields = ['observation']
    success_url = reverse_lazy(
            viewname='appointments:list_requests',
    )
    pk_url_kwarg = 'request_pk'

    def form_valid(self, form):
        form.instance.status = AppointmentRequest.DECLINED
        form.save()
        return super(RequestUpdateStatusView, self).form_valid(form)


class RequestAfterResultDeleteView(LoginRequiredMixin, DeleteView):
    model = AppointmentRequest
    template_name = 'appointments/request_after_result_confirm_delete.html'
    success_url = reverse_lazy(
            viewname='appointments:list_requests',
    )
    pk_url_kwarg = 'request_pk'

drdown/appointments/templates/appointments/appointment_form.html
{% extends 'core/base.html' %}
{% load static i18n %}

{% block title %}
  {% url 'appointments:create_appointment' as url %}
  {% if request.path == url %}
    {% trans "New Appointment" %}
  {% else %}
    {% trans "Edit Appointment" %}
  {% endif %}
{% endblock %}

{% block content %}
<div class="col-md-6 offset-md-3">
  {% url 'appointments:create_appointment' as url %}
  {% if request.path == url %}
    <h1>{% trans "New Appointment" %}</h1>
  {% else %}
    <h1>{% trans "Edit Appointment" %}</h1>
  {% endif %}
  <form method="post" id="doctorForm" data-doctors-url="{% url 'appointments:ajax_load_doctors' %}" novalidate>
    {% csrf_token %}
    <div class="fieldWrapper form-group">
      <label for="id_speciality" class="col-form-label">{% trans 'Speciality' %}:</label>
        {% if object.speciality %}
        <select class= "select form-control" name="speciality"  disabled id="id_speciality">
          <option value="{{object.speciality}}" selected>{{object.get_speciality_display}}</option>
        {% else %}
        <select class= "select form-control" name="speciality"  required id="id_speciality">
          <option value="" selected>---------</option>
          <option value="Speech Therapy">{% trans 'Speech Therapy' %}</option>
          <option value="Psychology">{% trans 'Psychology' %}</option>
          <option value="Physiotherapy">{% trans 'Physiotherapy' %}</option>
          <option value="Occupational Therapy">{% trans 'Occupational Therapy' %}</option>
          <option value="Cardiology">{% trans 'Cardiology' %}</option>
          <option value="Neurology">{% trans 'Neurology' %}</option>
          <option value="Pediatrics">{% trans 'Pediatrics' %}</option>
          <option value="General Practitioner">{% trans 'General Practitioner' %}</option>
        {% endif %}
      </select>
    </div>

    <div class="fieldWrapper form-group">
      <label for="id_doctor" class="col-form-label">{% trans 'Doctor' %}:</label><br>
      <select name="doctor" class= "select form-control" required id="id_doctor" size="6">
        {% if object.doctor %}
          <option value="{{ object.doctor.pk }}" selected>{{ object.doctor.user.name }}</option>
            {% for doctor in health_team %}
              {% if doctor.pk != object.doctor.pk %}
              <option value="{{ doctor.pk }}">{{ doctor.user.name }}</option>
              {% endif %}
            {% endfor %}
        {% else %}
          {% for doctor in health_team %}
            <option value="{{ doctor.pk }}">{{ doctor.user.name }}</option>
          {% endfor %}
        {% endif %}

      </select>
    </div>

    <div class="fieldWrapper form-group">
      <label for="id_patient" class="col-form-label">{% trans 'Patient' %}:</label><br>
      <select name="patient" class= "select form-control" required id="id_patient" size="6">
        {% if object.patient %}
          <option value="{{ object.patient.pk }}" selected>{{ object.patient.user.name }}</option>
            {% for patient in patients %}
              {% if patient.pk != object.patient.pk %}
              <option value="{{ patient.pk }}">{{ patient.user.name }}</option>
              {% endif %}
            {% endfor %}
        {% else %}
          {% for patient in patients %}
            <option value="{{ patient.pk }}">{{ patient.user.name }}</option>
          {% endfor %}
        {% endif %}
      </select>
    </div>

    <div class="fieldWrapper form-group">
      <label for="id_date" class="col-form-label">{% trans 'Date' %}:</label>
      {% if object.date %}
        <input type="date" name="date" id="id_date" class="form-control" min="{% now 'Y-m-d' %}" value="{{ object.date | date:'Y-m-d' }}" required>
      {% else %}
        <input type="date" name="date" id="id_date" class="form-control" min="{% now 'Y-m-d' %}" required>
      {% endif %}
      <span class="validity"></span>
    </div>



    <div class="fieldWrapper form-group">
      <label for="id_time" class="col-form-label">{% trans 'Time' %}:</label>
      {% if object.time %}
        <input type="time" name="time" id="id_time" value="{{ object.time }}" class="form-control" required>
      {% else %}
        <input type="time" name="time" id="id_time" class="form-control" required>
      {% endif %}
      <span class="validity"></span>
    </div>
    <div class="float-right">
      <a href="{% url 'appointments:list_appointments' %}" class="btn btn-danger">{% trans 'Cancelar' %}</a>
      <button type="submit" class="btn btn-success">{% trans 'Schedule' %}</button>
    </div>
  </form>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>
    $("#id_speciality").change(function () {
      var url = $("#doctorForm").attr("data-doctors-url");  // get the url of the `load_cities` view
      var specialityId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'speciality': specialityId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_doctor").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });
  </script>
  
{% endblock %}

drdown/appointments/templates/appointments/request_list.html
{% extends "core/base.html" %}
{% load static i18n %}

{% block css %}
  {{block.super}}
  <link href="{% static 'appointments/css/appointment.css' %}" rel="stylesheet">
{% endblock %}

{% block title %}{% trans "Requests" %}{% endblock %}

{% block content %}
  <div class="container" >
    {% if request.user.patient and request.user.age >= 13 or request.user.responsible %}
      <a href="{% url 'appointments:create_request' %}" class="btn btn-secondary mt-1 float-right mr-3">{% trans "New Request" %}</a>
    {% endif %}
    <h2>{% trans 'Requests' %}</h2><hr>


    {% url 'appointments:list_requests' as url %}
   {% if request.path == url %}
   <div class="row ml-1 mb-3">
     <div id="search">
       <form class="form-inline " action="" method="GET">
         <select class="form-control" name="search_speciality" id="id_search_speciality">
           <option value="" selected>{% trans 'Speciality' %}</option>
           <option value="SPEECH THERAPY">{% trans 'Speech Theraphy' %}</option>
           <option value="PSYCHOLOGY">{% trans 'Psychology' %}</option>
           <option value="PHYSIOTHERAPY">{% trans 'Physiotherapy' %}</option>
           <option value="OCCUPATIONAL THERAPY">{% trans 'Occupational Therapy' %}</option>
           <option value="GENERAL PRACTITIONER">{% trans 'General Practitioner' %}</option>
           <option value="CARDIOLOGY">{% trans 'Cardiology' %}</option>
           <option value="NEUROLOGY">{% trans 'Neurology' %}</option>
           <option value="PEDIATRICS">{% trans 'Pediatrics' %}</option>
         </select>
         <div class="row ml-3 mr-3">
         <input type="text" style="max-width: 180px;" class="form-control" name="search_name" placeholder="{% trans 'Name' %}" id="id_search_name" />
         </div>
         <button class="btn fa fa-search ml-2 clear-" style="background-color:LightGray" type="submit">{% trans "Search" %}</button>

       </form>
     </div>
    </div>
   {% endif %}

    {% for appointmentrequest in appointmentrequest_list %}
      <div class="media mb-2 media-body dialogalog body border-top border-bottom" id="request">
        <div class="message" style="width:98%">
          {% if request.user.patient or request.user.responsible %}
            {% if appointmentrequest.status != 'Declined' and appointmentrequest.status != 'Scheduled' %}
              <a data-toggle="modal" data-target="#appointmentrequest-{{ appointmentrequest.id }} delete_request" href="" class="btn mt-1 btn-danger btn-sm float-right mr-2">{% trans "Delete" %}</a>
              <a href="{% url 'appointments:update_request' appointmentrequest.pk %}" class="btn mt-1 btn-secondary btn-sm float-right mr-2">{% trans "Edit" %}</a>
            {% else %}
              <a href="{% url 'appointments:delete_request_after_result' appointmentrequest.pk  %}" class="btn mt-1 btn-success btn-sm float-right mr-2 mt-1">{% trans "OK" %}!</a>
            {% endif %}
          {% elif request.user.employee and appointmentrequest.status != 'Declined' and appointmentrequest.status != 'Scheduled' %}
            <a href="{% url 'appointments:create_from_request' appointmentrequest.pk %}" class="btn mt-1 btn-success btn-sm float-right mr-2">{% trans "Accept" %}</a>
            <a href="{% url 'appointments:update_status_request' appointmentrequest.pk %}" class="btn mt-1 btn-danger btn-sm float-right mr-2">{% trans "Decline" %}</a>
          {% endif %}
          <h5 class="mt-2">{% trans 'Patient'%}: {{appointmentrequest.patient.user.name}}</h5>
          {% if appointmentrequest.doctor.user.name == none %}
            <font size="3" >{% trans 'Doctor'%}: {% trans 'Does not have doctor preference'%}</font><br>
          {% else %}
            <font size="3" >{% trans 'Doctor'%}: {{ appointmentrequest.doctor.user.name}}</font><br>
          {% endif %}
          <font size="2" >{% trans 'Especiality'%}: {{appointmentrequest.get_speciality_display}}</font><br>
          <font size="2" >{% trans 'Shift'%}: {{appointmentrequest.get_shift_display}}</font><br>
          <font size="2" >{% trans 'Day of the week'%}: {{appointmentrequest.get_day_display}}</font><br>
          {% if appointmentrequest.motive %}
            <font size="2" >{% trans 'Motive'%}: {{appointmentrequest.motive}}</font><br>
          {% endif %}
          <br/>
          <div class="row">
          <div class="col-auto">
            <p class= "form-control"  > <font size="3" >{% trans 'Status'%}: {{appointmentrequest.get_status_display}} </font><br></p>
          </div>
            <div class="col-auto"></div>
          </div>
            {% if request.user.employee %}
            <font size="2" >{% trans 'Risk'%}: {{appointmentrequest.get_risk_display}}</font><br>
          {% endif %}
          {% if appointmentrequest.observation %}
            <font size="2" >{% trans 'Observation'%}: {{appointmentrequest.observation}}</font><br>
          {% endif %}
        </div>
      </div>

        <!-- Delete request modal -->
        <div class="modal fade" id="appointmentrequest-{{ appointmentrequest.id }} delete_request" role="dialog">
          <div class="modal-dialog modal-sm modal-dialog-centered">
            <div class="modal-content">
              <div class="modal-header">
                <h4 class="modal-title">{% trans 'Confirm delete' %}</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
              </div>
              <div class="modal-body">
                <p>{% trans 'Are you sure you want to delete this request?' %} </p>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Cancel' %}</button>
                <form method="post" action="{% url 'appointments:delete_request' appointmentrequest.pk %}">
                  {% csrf_token %}
                  <button class="btn btn-danger float-right" type="submit">{% trans 'Delete' %}</button>
                </form>
              </div>
            </div>
          </div>
        </div>

    {% empty %}
      <h4 class="lead text-secondary" align="center">{% trans 'There are no requests'%}</h4>
    {% endfor %}
  </div>

  {% include "core/pagination.html" %}


{% endblock %}